-- +goose Up
-- +goose StatementBegin
INSERT INTO users_post (creator_id, text_content) VALUES
('1', 'Quick tip: Always use `go fmt`! Your future self will thank you. 🚀 #GoLang #CodingTips'),
('1', 'Just discovered a neat trick with goroutines. Concurrency is fun! ✨ #GoConcurrency'),
('1', 'Debugging a tricky bug. Sometimes, a fresh pair of eyes is all you need. 👀 #Debugging'),
('2', 'Golden hour is magic for portraits. Don''t miss it! 🌅 #PhotographyTips'),
('2', 'Experimenting with long exposure tonight. Wish me luck! 📸 #LongExposure'),
('2', 'A good composition can make any photo stunning. Rule of thirds, anyone? 🤔 #Composition'),
('3', 'Nothing beats the view from the top! ⛰️ #HikingAdventures'),
('3', 'Found a hidden waterfall today. Nature''s beauty is endless. 💧 #NatureLover'),
('3', 'Quick tip for hikers: always pack extra socks! You never know. 🧦 #HikingTips'),
('4', 'Always be prepared. A well-stocked bug-out bag is essential. 🎒 #SurvivalTips'),
('4', 'Practicing knot-tying today. Essential skill for any situation. 🧵 #Tactical'),
('4', 'Quick tip: Water purification is key in the wild. Don''t risk it! 💧 #Wilderness'),
('5', 'Crushed my workout today! Consistency is key. 💪 #FitnessMotivation'),
('5', 'Just finished a challenging scene. Acting is all about connection. 🎭 #ActingLife'),
('5', 'Quick tip: Hydration is vital for performance, on stage or in the gym! 💧 #HealthTips'),
('6', 'My tomatoes are finally ripening! So rewarding. 🍅 #Gardening'),
('6', 'Baking a new sourdough recipe. The smell is divine! 🍞 #BakingLove'),
('6', 'Quick tip for gardeners: coffee grounds are great for acid-loving plants! ☕ #GardenTips'),
('7', 'Just upgraded my dev environment. So much faster now! 💻 #TechLife'),
('7', 'Enjoying a long ride today. Cycling clears the mind. 🚴‍♂️ #Cycling'),
('7', 'Quick tip: Always back up your code! You''ll thank yourself later. 💾 #DevTips'),
('8', 'Lost in my canvas today. Art is therapy. 🎨 #Painting'),
('8', 'Found so much inspiration in the forest. Nature''s palette is endless. 🌳 #NatureArt'),
('8', 'Quick tip for artists: don''t be afraid to experiment with new mediums! ✨ #ArtTips'),
('9', 'Just read a fascinating article on quantum entanglement. Mind blown! 🤯 #Science'),
('9', 'Trying out some new macro lenses. The world up close is amazing! 🔬 #MacroPhotography'),
('9', 'Quick tip: Good lighting is everything in photography. Find your light! 💡 #PhotoTips'),
('10', 'Rehearsals are intense but so much fun! Love the energy. 💃 #Dancing'),
('10', 'Working on character development today. Every role is a journey. 🎬 #Acting'),
('10', 'Quick tip for performers: warm-ups are non-negotiable! Protect your instrument. 🎤 #PerformanceTips');
-- +goose StatementEnd