package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/ctrixcode/ctrix-social-go-backend/internal/graphql/model"
)

// GetCommentByID is the resolver for the getCommentByID field.
func (r *queryResolver) GetCommentByID(ctx context.Context, id string) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: GetCommentByID - getCommentByID"))
}

// GetCommentsByPostID is the resolver for the getCommentsByPostID field.
func (r *queryResolver) GetCommentsByPostID(ctx context.Context, postID string) ([]*model.Comment, error) {
	panic(fmt.Errorf("not implemented: GetCommentsByPostID - getCommentsByPostID"))
}
