package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"time"

	"github.com/ctrixcode/ctrix-social-go-backend/internal/graphql/helpers"
	"github.com/ctrixcode/ctrix-social-go-backend/internal/graphql/model"
	pkgErrors "github.com/ctrixcode/ctrix-social-go-backend/pkg/errors"
)

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	requestedFields := helpers.GetRequestedFields(ctx)
	post, err := r.PostService.GetPostByIDWithFields(id, requestedFields)
	if err != nil {
		return nil, fmt.Errorf("failed to get post: %w", err)
	}
	if post == nil {
		return nil, fmt.Errorf("post not found")
	}

	// Ensure only creator can view their own post, or add logic for public/group posts
	if post.CreatorID != userID {
		return nil, fmt.Errorf("unauthorized to view this post")
	}

	return &model.Post{
		ID:               post.ID,
		GroupID:          post.GroupID,
		TextContent:      post.TextContent,
		PicturesAttached: post.PicturesAttached,
		CreatedAt:        post.CreatedAt.Format(time.RFC3339),
		UpdatedAt:        post.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// MyPosts is the resolver for the myPosts field.
func (r *queryResolver) MyPosts(ctx context.Context) ([]*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	requestedFields := helpers.GetRequestedFields(ctx)
	posts, err := r.PostService.GetPostsByCreatorIDWithFields(userID, requestedFields)
	if err != nil {
		return nil, fmt.Errorf("failed to get posts: %w", err)
	}
	// No need to check if posts is nil here, as pg_repository.go now returns an empty slice.

	var gqlPosts []*model.Post
	for _, post := range posts {
		var createdAt string
		if post.CreatedAt != nil {
			createdAt = post.CreatedAt.Format(time.RFC3339)
		}
		var updatedAt string
		if post.UpdatedAt != nil {
			updatedAt = post.UpdatedAt.Format(time.RFC3339)
		}

		gqlPosts = append(gqlPosts, &model.Post{
			ID:               post.ID,
			GroupID:          post.GroupID,
			TextContent:      post.TextContent,
			PicturesAttached: post.PicturesAttached,
			CreatedAt:        createdAt,
			UpdatedAt:        updatedAt,
		})
	}

	return gqlPosts, nil
}

// GetPostsByCreatorID is the resolver for the getPostsByCreatorID field.
func (r *queryResolver) GetPostsByCreatorID(ctx context.Context, creatorID string) ([]*model.Post, error) {
	requestedFields := helpers.GetRequestedFields(ctx)
	posts, err := r.PostService.GetPostsByCreatorIDWithFields(creatorID, requestedFields)
	if err != nil {
		return nil, pkgErrors.InternalServerError(pkgErrors.ErrSomethingWentWrong, err.Error())
	}
	if posts == nil {
		return nil, pkgErrors.NotFoundError(pkgErrors.ErrNotFound, "post not found")
	}

	var gqlPosts []*model.Post
	for _, post := range posts {
		var createdAt string
		if post.CreatedAt != nil {
			createdAt = post.CreatedAt.Format(time.RFC3339)
		}
		var updatedAt string
		if post.UpdatedAt != nil {
			updatedAt = post.UpdatedAt.Format(time.RFC3339)
		}

		gqlPosts = append(gqlPosts, &model.Post{
			ID:               post.ID,
			GroupID:          post.GroupID,
			TextContent:      post.TextContent,
			PicturesAttached: post.PicturesAttached,
			CreatedAt:        createdAt,
			UpdatedAt:        updatedAt,
		})
	}
	return gqlPosts, nil
}
