package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"time"

	"github.com/ctrixcode/ctrix-social-go-backend/internal/graphql/helpers"
	"github.com/ctrixcode/ctrix-social-go-backend/internal/graphql/model"
	"github.com/ctrixcode/ctrix-social-go-backend/internal/posts"
	"github.com/google/uuid"
	"github.com/lib/pq"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	now := time.Now()
	post := &posts.Post{
		ID:        uuid.New().String(),
		CreatorID: userID,
		CreatedAt: &now,
		UpdatedAt: &now,
	}

	if input.GroupID != nil {
		post.GroupID = input.GroupID
	}
	if input.TextContent != nil {
		post.TextContent = input.TextContent
	}
	if input.PicturesAttached != nil {
		post.PicturesAttached = pq.StringArray(input.PicturesAttached)
	}

	err := r.PostService.CreatePost(post)
	if err != nil {
		return nil, fmt.Errorf("failed to create post: %w", err)
	}

	requestedFields := helpers.GetRequestedFields(ctx)
	createdPost, err := r.PostService.GetPostByIDWithFields(post.ID, requestedFields)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve created post: %w", err)
	}

	return &model.Post{
		ID:               createdPost.ID,
		CreatorID:        createdPost.CreatorID,
		GroupID:          createdPost.GroupID,
		TextContent:      createdPost.TextContent,
		PicturesAttached: createdPost.PicturesAttached,
		CreatedAt:        createdPost.CreatedAt.Format(time.RFC3339),
		UpdatedAt:        createdPost.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input model.UpdatePostInput) (*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	post := &posts.Post{
		ID:        id,
		CreatorID: userID, // Ensure only creator can update
		// UpdatedAt is handled by PostgreSQL automatically
	}

	if input.GroupID != nil {
		post.GroupID = input.GroupID
	}
	if input.TextContent != nil {
		post.TextContent = input.TextContent
	}
	if input.PicturesAttached != nil {
		post.PicturesAttached = pq.StringArray(input.PicturesAttached)
	}

	err := r.PostService.UpdatePost(post)
	if err != nil {
		return nil, fmt.Errorf("failed to update post: %w", err)
	}

	requestedFields := helpers.GetRequestedFields(ctx)
	updatedPost, err := r.PostService.GetPostByIDWithFields(id, requestedFields)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve updated post: %w", err)
	}

	return &model.Post{
		ID:               updatedPost.ID,
		CreatorID:        updatedPost.CreatorID,
		GroupID:          updatedPost.GroupID,
		TextContent:      updatedPost.TextContent,
		PicturesAttached: updatedPost.PicturesAttached,
		CreatedAt:        updatedPost.CreatedAt.Format(time.RFC3339),
		UpdatedAt:        updatedPost.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	requestedFields := helpers.GetRequestedFields(ctx)
	post, err := r.PostService.GetPostByIDWithFields(id, requestedFields)
	if err != nil {
		return nil, fmt.Errorf("failed to get post: %w", err)
	}
	if post == nil {
		return nil, fmt.Errorf("post not found")
	}

	// Ensure only creator can view their own post, or add logic for public/group posts
	if post.CreatorID != userID {
		return nil, fmt.Errorf("unauthorized to view this post")
	}

	return &model.Post{
		ID:               post.ID,
		CreatorID:        post.CreatorID,
		GroupID:          post.GroupID,
		TextContent:      post.TextContent,
		PicturesAttached: post.PicturesAttached,
		CreatedAt:        post.CreatedAt.Format(time.RFC3339),
		UpdatedAt:        post.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// MyPosts is the resolver for the myPosts field.
func (r *queryResolver) MyPosts(ctx context.Context) ([]*model.Post, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	requestedFields := helpers.GetRequestedFields(ctx)
	posts, err := r.PostService.GetPostsByCreatorIDWithFields(userID, requestedFields)
	if err != nil {
		return nil, fmt.Errorf("failed to get posts: %w", err)
	}
	if posts == nil {
		return nil, fmt.Errorf("posts not found")
	}

	var createdAt *string
	if posts[0].CreatedAt != nil {
		s := posts[0].CreatedAt.Format(time.RFC3339)
		createdAt = &s
	}

	var updatedAt *string
	if posts[0].UpdatedAt != nil {
		s := posts[0].UpdatedAt.Format(time.RFC3339)
		updatedAt = &s
	}

	return []*model.Post{
		{
			ID:               posts[0].ID,
			CreatorID:        posts[0].CreatorID,
			GroupID:          posts[0].GroupID,
			TextContent:      posts[0].TextContent,
			PicturesAttached: posts[0].PicturesAttached,
			CreatedAt:        *createdAt,
			UpdatedAt:        *updatedAt,
		},
	}, nil
}
