package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/mcctrix/ctrix-social-go-backend/internal/graphql/model"
)

// CreateMyUserData is the resolver for the createMyUserData field.
func (r *mutationResolver) CreateMyUserData(ctx context.Context, input model.CreateUserDataInput) (*model.UserData, error) {
	panic(fmt.Errorf("not implemented: CreateMyUserData - createMyUserData"))
}

// UpdateMyUserData is the resolver for the updateMyUserData field.
func (r *mutationResolver) UpdateMyUserData(ctx context.Context, input model.UpdateUserDataInput) (*model.UserData, error) {
	panic(fmt.Errorf("not implemented: UpdateMyUserData - updateMyUserData"))
}

// MyUserData is the resolver for the myUserData field.
func (r *queryResolver) MyUserData(ctx context.Context) (*model.UserData, error) {
	panic(fmt.Errorf("not implemented: MyUserData - myUserData"))
}
