package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/mcctrix/ctrix-social-go-backend/internal/graphql/model"
)

// CreateMyUserProfile is the resolver for the createMyUserProfile field.
func (r *mutationResolver) CreateMyUserProfile(ctx context.Context, input model.CreateUserProfileInput) (*model.UserProfile, error) {
	panic(fmt.Errorf("not implemented: CreateMyUserProfile - createMyUserProfile"))
}

// UpdateMyUserProfile is the resolver for the updateMyUserProfile field.
func (r *mutationResolver) UpdateMyUserProfile(ctx context.Context, input model.UpdateUserProfileInput) (*model.UserProfile, error) {
	panic(fmt.Errorf("not implemented: UpdateMyUserProfile - updateMyUserProfile"))
}

// MyUserProfile is the resolver for the myUserProfile field.
func (r *queryResolver) MyUserProfile(ctx context.Context) (*model.UserProfile, error) {
	panic(fmt.Errorf("not implemented: MyUserProfile - myUserProfile"))
}
