package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/lib/pq"
	"github.com/mcctrix/ctrix-social-go-backend/internal/graphql/model"
	"github.com/mcctrix/ctrix-social-go-backend/internal/users_setting"
)

// UpdateMyUserSetting is the resolver for the updateMyUserSetting field.
func (r *mutationResolver) UpdateMyUserSetting(ctx context.Context, input model.UpdateUserSettingInput) (*model.UserSetting, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	userSetting := &users_setting.UserSetting{
		ID: userID,
	}

	if input.BlockUser != nil {
		userSetting.BlockUser = pq.StringArray(input.BlockUser)
	}
	if input.HidePost != nil {
		userSetting.HidePost = pq.StringArray(input.HidePost)
	}
	if input.HideStory != nil {
		userSetting.HideStory = pq.StringArray(input.HideStory)
	}
	if input.ShowOnline != nil {
		userSetting.ShowOnline = *input.ShowOnline
	}

	err := r.UserSettingService.UpdateSetting(userSetting)
	if err != nil {
		return nil, fmt.Errorf("failed to update user setting: %w", err)
	}

	updatedSetting, err := r.UserSettingService.GetSettingByID(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve updated user setting: %w", err)
	}

	return &model.UserSetting{
		BlockUser:  updatedSetting.BlockUser,
		HidePost:   updatedSetting.HidePost,
		HideStory:  updatedSetting.HideStory,
		ShowOnline: updatedSetting.ShowOnline,
	}, nil
}

// MyUserSetting is the resolver for the myUserSetting field.
func (r *queryResolver) MyUserSetting(ctx context.Context) (*model.UserSetting, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	userSetting, err := r.UserSettingService.GetSettingByID(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user setting: %w", err)
	}
	if userSetting == nil {
		return nil, fmt.Errorf("user setting not found")
	}

	return &model.UserSetting{
		BlockUser:  userSetting.BlockUser,
		HidePost:   userSetting.HidePost,
		HideStory:  userSetting.HideStory,
		ShowOnline: userSetting.ShowOnline,
	}, nil
}
