// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserProfileInput struct {
	FirstName      *string  `json:"firstName,omitempty"`
	LastName       *string  `json:"lastName,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Avatar         *string  `json:"avatar,omitempty"`
	RelationStatus *string  `json:"relationStatus,omitempty"`
	Dob            *string  `json:"dob,omitempty"`
	Bio            *string  `json:"bio,omitempty"`
	Gender         *string  `json:"gender,omitempty"`
	FamilyMembers  []string `json:"familyMembers,omitempty"`
	Hobbies        []string `json:"hobbies,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserProfileInput struct {
	FirstName      *string  `json:"firstName,omitempty"`
	LastName       *string  `json:"lastName,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Avatar         *string  `json:"avatar,omitempty"`
	RelationStatus *string  `json:"relationStatus,omitempty"`
	Dob            *string  `json:"dob,omitempty"`
	Bio            *string  `json:"bio,omitempty"`
	Gender         *string  `json:"gender,omitempty"`
	FamilyMembers  []string `json:"familyMembers,omitempty"`
	Hobbies        []string `json:"hobbies,omitempty"`
}

type UpdateUserSettingInput struct {
	BlockUser  []string `json:"blockUser,omitempty"`
	HidePost   []string `json:"hidePost,omitempty"`
	HideStory  []string `json:"hideStory,omitempty"`
	ShowOnline *bool    `json:"showOnline,omitempty"`
}

type UserProfile struct {
	FirstName      *string  `json:"firstName,omitempty"`
	LastName       *string  `json:"lastName,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Avatar         *string  `json:"avatar,omitempty"`
	RelationStatus *string  `json:"relationStatus,omitempty"`
	Dob            *string  `json:"dob,omitempty"`
	Bio            *string  `json:"bio,omitempty"`
	Gender         *string  `json:"gender,omitempty"`
	FamilyMembers  []string `json:"familyMembers,omitempty"`
	Hobbies        []string `json:"hobbies,omitempty"`
}

type UserSetting struct {
	BlockUser  []string `json:"blockUser"`
	HidePost   []string `json:"hidePost"`
	HideStory  []string `json:"hideStory"`
	ShowOnline bool     `json:"showOnline"`
}
