// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID         string `json:"id"`
	Username   string `json:"username"`
	ProfilePic string `json:"profilePic"`
	Avatar     string `json:"avatar"`
}

type Comment struct {
	ID               string   `json:"id"`
	PostID           string   `json:"postID"`
	CreatorID        string   `json:"creatorID"`
	Content          string   `json:"content"`
	PicturesAttached []string `json:"picturesAttached,omitempty"`
	CreatedAt        string   `json:"createdAt"`
	UpdatedAt        string   `json:"updatedAt"`
	Author           *Author  `json:"author"`
}

type Mutation struct {
}

type Post struct {
	ID               string   `json:"id"`
	GroupID          *string  `json:"groupID,omitempty"`
	TextContent      *string  `json:"textContent,omitempty"`
	PicturesAttached []string `json:"picturesAttached,omitempty"`
	CreatedAt        string   `json:"createdAt"`
	UpdatedAt        string   `json:"updatedAt"`
}

type Query struct {
}

type UpdateUserDataInput struct {
	LastSeen   *string  `json:"lastSeen,omitempty"`
	Followers  []string `json:"followers,omitempty"`
	Followings []string `json:"followings,omitempty"`
}

type UpdateUserProfileInput struct {
	FirstName      *string  `json:"firstName,omitempty"`
	LastName       *string  `json:"lastName,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Avatar         *string  `json:"avatar,omitempty"`
	RelationStatus *string  `json:"relationStatus,omitempty"`
	Dob            *string  `json:"dob,omitempty"`
	Bio            *string  `json:"bio,omitempty"`
	Gender         *string  `json:"gender,omitempty"`
	FamilyMembers  []string `json:"familyMembers,omitempty"`
	Hobbies        []string `json:"hobbies,omitempty"`
}

type UpdateUserSettingInput struct {
	BlockUser  []string `json:"blockUser,omitempty"`
	HidePost   []string `json:"hidePost,omitempty"`
	HideStory  []string `json:"hideStory,omitempty"`
	ShowOnline *bool    `json:"showOnline,omitempty"`
}

type UserData struct {
	LastSeen   *string  `json:"lastSeen,omitempty"`
	Followers  []string `json:"followers,omitempty"`
	Followings []string `json:"followings,omitempty"`
}

type UserProfile struct {
	FirstName      *string  `json:"firstName,omitempty"`
	LastName       *string  `json:"lastName,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Avatar         *string  `json:"avatar,omitempty"`
	RelationStatus *string  `json:"relationStatus,omitempty"`
	Dob            *string  `json:"dob,omitempty"`
	Bio            *string  `json:"bio,omitempty"`
	Gender         *string  `json:"gender,omitempty"`
	FamilyMembers  []string `json:"familyMembers,omitempty"`
	Hobbies        []string `json:"hobbies,omitempty"`
}

type UserSetting struct {
	BlockUser  []string `json:"blockUser"`
	HidePost   []string `json:"hidePost"`
	HideStory  []string `json:"hideStory"`
	ShowOnline bool     `json:"showOnline"`
}
